#!/data/data/com.termux/files/usr/bin/bash
#rm -rf * && rm -rf "$PREFIX/bin/andistro_files/" && rm -rf "$PREFIX/bin/andistro"
if [ ! -d "$PREFIX/bin/andistro_files/" ];then
	mkdir -p "$PREFIX/bin/andistro_files/"
fi
extralink="https://raw.githubusercontent.com/andistro/app/main"
system_icu_locale_code=$(getprop persist.sys.locale)

apt update > /dev/null 2>&1 && apt upgrade -y

if [ ! -d "$HOME/storage" ];then
    termux-setup-storage
fi
# Log de erros
if [ ! -d "$HOME/storage/shared/termux/andistro_logs" ];then
    mkdir "$HOME/storage/shared/termux/"
    mkdir "$HOME/storage/shared/termux/andistro_logs"
fi

clear

# ==============================================================================================
# GLOBAL
# ==============================================================================================
# Variável com o link do script no GitHub
# Função para atualizar a barra de progresso
# update_progress() precisa ser definido antes de ser usado
update_progress() {
    current_step=$1
    total_steps=$2

    percent=$((current_step * 100 / total_steps))
    bar_length=30
    filled_length=$((percent * bar_length / 100))
    empty_length=$((bar_length - filled_length))

    filled_bar=$(printf "%${filled_length}s" | tr " " "=")
    empty_bar=$(printf "%${empty_length}s" | tr " " " ")

    printf "\r[%s%s] %3d%%" "$filled_bar" "$empty_bar" "$percent"
}


total_steps=11  # Número total de etapas que você quer monitorar
current_step=0

{
    #1 Verifica se o termux-exec está instalado
    if ! dpkg -l | grep -qw proot; then
        apt install termux-exec -y
    fi
    ((current_step++))
    update_progress "$current_step" "$total_steps"; sleep 0.1

    #2 Verifica se o proot está instalado
    if ! dpkg -l | grep -qw proot; then
        apt install proot -y
    fi
    ((current_step++))
    update_progress "$current_step" "$total_steps"; sleep 0.1

    #3 Verifica se o wget está instalado
    if ! dpkg -l | grep -qw wget; then
        apt install wget -y
    fi
    ((current_step++))
    update_progress "$current_step" "$total_steps"; sleep 0.1

    #4 Verifica se o dialog está instalado
    if ! dpkg -l | grep -qw dialog; then
        apt install dialog -y
    fi
    ((current_step++))
    update_progress "$current_step" "$total_steps"; sleep 0.1

    #5 Verifica se o tar está instalado
    if ! dpkg -l | grep -qw tar; then
        apt install tar -y
    fi
    ((current_step++))
    update_progress "$current_step" "$total_steps"; sleep 0.1

    #6 Verifica se o curl está instalado
    if ! dpkg -l | grep -qw curl; then
        apt install curl -y
    fi
    ((current_step++))
    update_progress "$current_step" "$total_steps"; sleep 0.1

    #7 Verifica e baixa fixed_variables.sh
    if [ ! -f "$PREFIX/bin/andistro_files/fixed_variables.sh" ]; then
        curl -s -o "$PREFIX/bin/andistro_files/fixed_variables.sh" "${extralink}/config/fixed_variables.sh"
        else
            curl -s -o "$PREFIX/bin/andistro_files/fixed_variables.check" "${extralink}/config/fixed_variables.sh"
            if [ -f "$PREFIX/bin/andistro_files/fixed_variables.sh" ] && [ -f "$PREFIX/bin/andistro_files/fixed_variables.check" ]; then
                if ! cmp -s "$PREFIX/bin/andistro_files/fixed_variables.sh" "$PREFIX/bin/andistro_files/fixed_variables.check"; then
                    rm "$PREFIX/bin/andistro_files/fixed_variables.sh"
                    mv "$PREFIX/bin/andistro_files/fixed_variables.check" "$PREFIX/bin/andistro_files/fixed_variables.sh"
                    chmod +x "$PREFIX/bin/andistro_files/fixed_variables.sh"
                    status_atualizacao_andistro_1="*Houve uma atualização dos modulos globais!"
                else
                    rm "$PREFIX/bin/andistro_files/fixed_variables.check"
                fi
            fi
    fi
    ((current_step++))
    update_progress "$current_step" "$total_steps"; sleep 0.1

    #8 Verifica e baixa l10n_${locale}.sh
    if [ ! -f "$PREFIX/bin/andistro_files/l10n_${system_icu_locale_code}.sh" ]; then
        curl -s -o "$PREFIX/bin/andistro_files/l10n_${system_icu_locale_code}.sh" "${extralink}/config/locale/l10n_${system_icu_locale_code}.sh"
        else
            curl -s -o "$PREFIX/bin/andistro_files/l10n_${system_icu_locale_code}.sh" "${extralink}/config/locale/l10n_${system_icu_locale_code}.sh"
            if [ -f "$PREFIX/bin/andistro_files/l10n_${system_icu_locale_code}.sh" ] && [ -f "$PREFIX/bin/andistro_files/l10n_${system_icu_locale_code}.check" ]; then
                if ! cmp -s "$PREFIX/bin/andistro_files/l10n_${system_icu_locale_code}.sh" "$PREFIX/bin/andistro_files/l10n_${system_icu_locale_code}.check"; then
                    rm "$PREFIX/bin/andistro_files/l10n_${system_icu_locale_code}.sh"
                    mv "$PREFIX/bin/andistro_files/l10n_${system_icu_locale_code}.check" "$PREFIX/bin/andistro_files/l10n_${system_icu_locale_code}.sh"
                    chmod +x "$PREFIX/bin/andistro_files/l10n_${system_icu_locale_code}.sh"
                    status_atualizacao_andistro_2="*Houve uma atualização do pacote de idioma!"
                else
                    rm "$PREFIX/bin/andistro_files/l10n_${system_icu_locale_code}.check"
                fi
            fi
    fi
    ((current_step++))
    update_progress "$current_step" "$total_steps"; sleep 0.1

    #9 Verifica se o andistro está em $HOME
    if [ -f "$HOME/andistro" ]; then
        mv "$HOME/andistro" "$PREFIX/bin/andistro"
        rm -rf "$HOME/andistro"
    fi
    chmod +x "$PREFIX/bin/andistro"
    ((current_step++))
    update_progress "$current_step" "$total_steps"; sleep 0.1

    #10 Baixa uma versão para comparação
    if [ ! -f "$HOME/andistro.check" ]; then
        curl -s -o "$HOME/andistro.check" "${extralink}/andistro"
    fi
    ((current_step++))
    update_progress "$current_step" "$total_steps"; sleep 0.1

    #11 Verifica e substitui se for necessário
    if [ -f "$PREFIX/bin/andistro" ] && [ -f "$HOME/andistro.check" ]; then
        if ! cmp -s "$PREFIX/bin/andistro" "$HOME/andistro.check"; then
            rm "$PREFIX/bin/andistro"
            mv "$HOME/andistro.check" "$PREFIX/bin/andistro"
            chmod +x "$PREFIX/bin/andistro"
            status_atualizacao_andistro="Houve uma atualização finalizada com sucesso!"
        else
            rm "$HOME/andistro.check"
        fi
    fi
    ((current_step++))
    update_progress "$current_step" "$total_steps"; sleep 0.1

    echo  # pular linha no fim
}

clear

chmod +x "$PREFIX/bin/andistro_files/fixed_variables.sh"
chmod +x "$PREFIX/bin/andistro_files/l10n_${system_icu_locale_code}.sh"
source "$PREFIX/bin/andistro_files/fixed_variables.sh"
source "$PREFIX/bin/andistro_files/l10n_${system_icu_locale_code}.sh"
#=============================================================================================
# COMANDOS
#=============================================================================================

# Verifica os argumentos passados ao script
if [ -z "$1" ]; then
    # Caso nenhum argumento seja passado, exibe a mensagem de instrução
    if [[ -n "$status_atualizacao_andistro" ]]; then
        exit
        andistro
        echo -e "Sistema atualizado"
    echo " "
    fi
    echo -e "Use: andistro <comando> <opção> para seja feito a tarefa desejada."
    echo ""
    echo -e "Exemplo de comando que permite a instalação:"
    echo -e "   andistro instalar debian"
    echo " "
    echo -e "Exemplo de comando que permite a desinstalação:"
    echo -e "   andistro desinstalar debian"
    echo " "
    echo -e "Exemplo de comando que permite a inicialização:"
    echo -e "   andistro iniciar debian"
    echo " "
    echo -e "Comandos:"
    echo -e "    instalar    - instala a opção escolhida."
    echo -e "    desinstalar - desinstala a opção escolhida."
    echo -e "    iniciar     - inicializa a versão escolhida."
    echo " "
    echo -e "Opções:"
    echo -e "   debian"
    echo -e "   ubuntu"
    echo " "
exit 0

fi

case "$1" in
    instalar)
        if [ -z "$2" ]; then
            echo -e "Use: andistro <comando> <opção> para seja feito a tarefa desejada."
            echo ""
            echo -e "Exemplo de comando que permite a instalação:"
            echo -e "   andistro instalar debian"
            echo " "
            echo -e "Comandos:"
            echo -e "    instalar    - instala a opção escolhida."
            echo " "
            echo -e "Opções:"
            echo -e "   debian"
            echo -e "   ubuntu"
            echo " "
            exit 1
        fi

        if [ "$2" == "debian" ]; then
            echo -e "Instalando o Debian...\nAguarde..."
            show_progress_dialog "wget" "${label_progress}" 1 -O "$HOME/start-distro.sh" "${extralink}/distros/debian.sh"
            clear

        elif [ "$2" == "ubuntu" ]; then
            echo -e "Instalando o Ubuntu...\nAguarde..."
            show_progress_dialog "wget" "${label_progress}" 1 -O "$HOME/start-distro.sh" "${extralink}/distros/ubuntu.sh"
            clear

        else
            echo "Distribuição não reconhecida: $2"
            exit 1
        fi
        chmod +x $HOME/start-distro.sh
        bash $HOME/start-distro.sh
        rm -rf $HOME/start-distro.sh
        ;;
    desinstalar)
        if [ -z "$2" ]; then
            echo -e "Use: andistro <comando> <opção> para seja feito a tarefa desejada."
            echon ""
            echo -e "Exemplo de comando que permite a desinstalação do Debian:"
            echo -e "   andistro desinstalar debian"
            echo " "
            echo -e "Comandos:"
            echo -e "    desinstalar - desinstala a opção escolhida."
            echo " "
            echo -e "Opções:\n"
            echo -e "   debian\n"
            echo -e "   ubuntu\n"
            echo " "
            exit 1
        fi

        if [ "$2" == "debian" ]; then
            echo -e "Desinstalando o Debian...\nAguarde..."
            rm -rf $HOME/debian-stable
            rm -rf $HOME/debian-binds
            rm -rf $HOME/start-debian.sh
            rm -rf $HOME/start-distro.sh
            rm -rf $HOME/l10n*.sh
            rm -rf $HOME/fixed_variables.sh
            rm -rf $HOME/storage
            rm -rf $HOME/debian-stable
            rm -rf $HOME/debian-bookworm
            rm -rf $HOME/debian-bullseye
            rm -rf $PREFIX/bin/start-debian
            rm -rf /data/data/com.termux/files/usr/var/run/dbus/pid 
            rm -rf system_bus_socket
            echo "Desinstalação concluída!"
            clear

        elif [ "$2" == "ubuntu" ]; then
            echo -e "Desinstalando o Ubuntu...\nAguarde..."
            rm -rf $HOME/ubuntu-fs
            rm -rf $HOME/ubuntu-binds
            rm -rf $HOME/start-ubuntu.sh
            rm -rf $HOME/start-distro.sh
            rm -rf $HOME/l10n*.sh
            rm -rf $HOME/fixed_variables.sh
            rm -rf $PREFIX/bin/start-ubuntu
            rm -rf /data/data/com.termux/files/usr/var/run/dbus/pid 
            rm -rf system_bus_socket
            echo "Desinstalação concluída!"
            clear

        else
            echo "Distribuição não reconhecida: $2"
            exit 1
        fi
        ;;
    iniciar)
        if [ -z "$2" ]; then
            echo -e "Use: andistro <comando> <opção> para seja feito a tarefa desejada."
            echo -e "Exemplo de comando que permite a inicialização:"
            echo -e "   andistro iniciar debian"
            echo " "
            echo -e "Comandos:"
            echo -e "    iniciar     - inicia a versão escolhida."
            echo " "
            echo -e "Opções:"
            echo -e "   debian"
            echo -e "   ubuntu"

            exit 1
        fi

        if [ "$2" == "debian" ]; then
            echo -e "Iniciando o Debian...\nAguarde..."
            start-debian
            clear

        elif [ "$2" == "ubuntu" ]; then
            echo -e "Iniciando o Ubuntu...\nAguarde..."
            start-ubuntu
            clear

        else
            echo "Distribuição não reconhecida: $2"
            exit 1
        fi
        ;;
    *)
        echo "Comando não reconhecido: $1"
        echo ""
        echo -e "Use: andistro <comando> <opção> para seja feito a tarefa desejada."
        echo ""
        echo -e "Exemplo de comando que permite a instalação:"
        echo -e "   andistro instalar debian"
        echo " "
        echo -e "Exemplo de comando que permite a desinstalação:"
        echo -e "   andistro desinstalar debian"
        echo " "
        echo -e "Exemplo de comando que permite a inicialização:"
        echo -e "   andistro iniciar debian"
        echo " "
        echo -e "Comandos:"
        echo -e "    instalar    - instala a opção escolhida."
        echo -e "    desinstalar - desinstala a opção escolhida."
        echo -e "    iniciar     - inicializa a versão escolhida."
        echo " "
        echo -e "Opções:"
        echo -e "   debian"
        echo -e "   ubuntu"
        echo " "
        exit 1
        ;;
esac
