#!/bin/bash

# URL do arquivo para download
url="https://partner-images.canonical.com/core/jammy/current/ubuntu-jammy-core-cloudimg-arm64-root.tar.gz"

# Nome do arquivo
filename="ubuntu-jammy-core-cloudimg-arm64-root.tar.gz"

# Iniciar o download em segundo plano e ocultar a saída
wget -O "$filename" "$url" > /dev/null 2>&1 &

# Configurar o intervalo de atualização da caixa de diálogo
interval=1

# Criar a caixa de diálogo
(
  while pkill -0 wget >/dev/null 2>&1; do
    sleep $interval
    echo "Em andamento..."
    echo "$((++percentage))"
  done
  echo "Em andamento..."
  echo "100"
  sleep 2
) | whiptail --gauge "Em andamento" 7 50 0

# Limpar a tela
clear