#!/data/data/com.termux/files/usr/bin/bash

# Variável com o link do script no GitHub
extralink="https://raw.githubusercontent.com/distribuicoeslinuxnoandroid/app/main"

#=============================================================================================
# VERIFICA ATUALIZAÇÕES DE DO CÓDIGO 
#=============================================================================================
script_url="${extralink}/instalar"

# Nome do arquivo local
local_script="instalar"

# Função para verificar e atualizar o script
update_script() {
    echo "Verificando atualizações do script..."

    # Baixa a versão mais recente do script do GitHub
    wget -q "$script_url" -O "${local_script}.new"

    # Verifica se o download foi bem-sucedido
    if [ $? -eq 0 ]; then
    # Compara a versão local com a versão do GitHub
        diff -q "$local_script" "${local_script}.new" > /dev/null 2>&1
        if [ $? -ne 0 ]; then
            echo "Atualização disponível. Substituindo o script local."
            # Substitui o script local pelo novo
            mv "${local_script}.new" "$local_script"
            chmod +x "$local_script"
            echo "Script atualizado com sucesso!"
            else
                echo "Script já está na versão mais recente."
                rm "${local_script}.new"  # Remove o arquivo temporário
            fi
        else
        echo "Falha ao baixar a atualização do script."
    fi
}

# Executa a função de atualização
update_script

#=============================================================================================
#=============================================================================================

# Verifica os argumentos passados ao script
if [ -z "$1" ]; then
    # Caso nenhum argumento seja passado, exibe a mensagem de instrução
    echo -e "Digite o comando 'instalar' seguido do nome da distribuição.\n
    Exemplo: instalar <NOME_DA_DISTRIBUIÇÃO> \n\n
    Comandos:\n
    debian:      instala o sistema Debian.\n
    ubuntu:      instala o sistema Ubuntu."
else
    # Executa os comandos comuns para qualquer distribuição
    echo -e "Iniciando a instalação\nAguarde..."
    termux-setup-storage
    apt install wget curl proot tar dialog whiptail -y > /dev/null 2>&1 &    
    extralink="https://raw.githubusercontent.com/distribuicoeslinuxnoandroid/app/main"
    system_icu_locale_code=$(getprop persist.sys.locale)
    
    # Baixa e executa o arquivo fixed_variables.sh
    if [ -f "fixed_variables.sh" ]; then
        source fixed_variables.sh
    else
        (
            echo 0  # Inicia em 0%
            wget --tries=20 "${extralink}/config/fixed_variables.sh" --progress=dot:giga 2>&1 | while read -r line; do
                # Extraindo a porcentagem do progresso do wget
                if [[ $line =~ ([0-9]+)% ]]; then
                    percent=${BASH_REMATCH[1]}
                    echo $percent  # Atualiza a barra de progresso
                fi
            done

            echo 50  # Finaliza em 50%
        ) | whiptail --gauge " " 5 40 0

        chmod +x fixed_variables.sh
        source fixed_variables.sh
    fi

    # Baixa e executa o arquivo l10n_<locale>.sh
    if [ -f "l10n_${system_icu_locale_code}.sh" ]; then
        source l10n_$system_icu_locale_code.sh
    else
        (
            echo 51  # Inicia em 51%
            wget --tries=20 "${extralink}/config/locale/l10n_${system_icu_locale_code}.sh" --progress=dot:giga 2>&1 | while read -r line; do
                # Extraindo a porcentagem do progresso do wget
                if [[ $line =~ ([0-9]+)% ]]; then
                    percent=${BASH_REMATCH[1]}
                    echo $percent  # Atualiza a barra de progresso
                fi
            done

            echo 100  # Finaliza em 100%
        ) | whiptail --gauge " " 5 40 0

        chmod +x l10n_$system_icu_locale_code.sh
        source l10n_$system_icu_locale_code.sh
    fi

    # Verifica qual distribuição foi escolhida e executa os comandos específicos
    if [ "$1" == "distro" ]; then
        echo -e "Aguarde..."
        OPTIONS=(1 "Debian"
                 2  "Ubuntu")

        CHOICE=$(dialog --clear \
                        --title "$TITLE" \
                        --menu "$MENU_operating_system_select" \
                        $HEIGHT $WIDTH $CHOICE_HEIGHT \
                        "${OPTIONS[@]}" \
                        2>&1 >/dev/tty)

        clear
        case $CHOICE in
        1)
            echo "Debian"
            instalar debian
            ;;
        2)
            echo "Ubuntu  [Teste]"
            instalar ubuntu  
        ;;

        esac
        
    
    elif [ "$1" == "debian" ]; then
        echo -e "Instalando o Debian...\nAguarde..."
        wget --tries=20 "${extralink}/distros/debian.sh" -O start-distro.sh > /dev/null 2>&1 &

        (
            while pkill -0 wget >/dev/null 2>&1; do
            sleep $whiptail_intervalo

            echo "${label_progress}"

            echo "$((++percentage))"
            done

            echo "${label_progress}"

            echo "75"
            sleep 2
        ) | whiptail --gauge "${label_progress}" 0 0 0
        clear

    
    elif [ "$1" == "ubuntu" ]; then
        echo -e "Instalando o Ubuntu...\nAguarde..."
        wget --tries=20 "${extralink}/distros/ubuntu.sh" -O start-distro.sh > /dev/null 2>&1 &

        (
            while pkill -0 wget >/dev/null 2>&1; do
            sleep $whiptail_intervalo

            echo "${label_progress}"

            echo "$((++percentage))"
            done

            echo "${label_progress}"

            echo "75"
            sleep 2
        ) | whiptail --gauge "${label_progress}" 0 0 0
        clear
        
    else
        echo "Distribuição não reconhecida: $1"
    fi

    # Comandos comuns após instalação de Debian ou Ubuntu:
    chmod +x start-distro.sh
    bash start-distro.sh
fi
