#!/data/data/com.termux/files/usr/bin/bash
pkg install dialog -y
clear
#Logs do sistema
android_version=$(getprop ro.build.version.release)
android_architecture=$(getprop ro.product.cpu.abi)
device_manufacturer=$(getprop ro.product.manufacturer)
device_model=$(getprop ro.product.model)
device_model_complete=$(getprop ril.product_code)
device_hardware=$(getprop ro.hardware.chipname)
system_country=$(getprop ro.csc.country_code)
system_country_iso=$(getprop ro.csc.countryiso_code)
system_icu_locale_code=$(getprop persist.sys.locale)
system_timezone=$(getprop persist.sys.timezone)
GMT_date=$(date +"%Z")

# Traduções
## Português do Brasil
separator_infos="----------"
pt_BR_title="Informações do seu sistema"
pt_BR_version_release="Versão do Android"
pt_BR_product_manufacturer="Marca"
pt_BR_model="Modelo"
pt_BR_hardware_chipname="Chipset"
pt_BR_chip_architecture="Arquitetura do chipset"
pt_BR_country="Região"
pt_BR_country_iso="Abreviação"
pt_BR_locale_code="Código do idioma"
pt_BR_timezone="Fuso horário do sistema"
if [ "$system_country" = "Brazil" ]; then
system_country="Brasil"
fi

# dialog --msgbox "${}" 0 0
if [ "$system_icu_locale_code" = "pt-BR" ]; then
dialog --msgbox "${pt_BR_title} \n
${separator_infos} \n
${pt_BR_version_release}: ${android_version} \n
${pt_BR_product_manufacturer}: ${device_manufacturer} \n
${pt_BR_model}: ${device_model} / ${device_model_complete} \n
${separator_infos} \n
${pt_BR_hardware_chipname}: ${device_hardware} \n
${pt_BR_chip_architecture}: ${android_architecture} \n
${separator_infos} \n
${pt_BR_country}: ${system_country} \n
${pt_BR_country_iso}: ${system_country_iso} \n
${pt_BR_locale_code}: ${system_icu_locale_code} \n
${pt_BR_timezone}: (GMT${GMT_date}:00) ${system_timezone} \n" 0 0
fi
clear



