#!/bin/bash
extralink="https://raw.githubusercontent.com/andistro/app/main"
system_icu_locale_code=$(echo $LANG | sed 's/\..*//' | sed 's/_/-/')


if [ -f "fixed_variables.sh" ]; then
	chmod +x fixed_variables.sh
	source fixed_variables.sh
	else
		(
				echo 0  # Inicia em 0%
				wget --tries=20 "${extralink}/config/fixed_variables.sh" --progress=dot:giga 2>&1 | while read -r line; do
					# Extraindo a porcentagem do progresso do wget
					if [[ $line =~ ([0-9]+)% ]]; then
						percent=${BASH_REMATCH[1]}
						echo $percent  # Atualiza a barra de progresso
					fi
				done

				echo 50  # Finaliza em 50%
			) | dialog --gauge "${label_progress}" 6 40 0

		chmod +x fixed_variables.sh
		source fixed_variables.sh
fi

## Variáveis de idioma. Que irão se adequar ao idioma escolhido
if [ -f "l10n_${system_icu_locale_code}.sh" ]; then
	source l10n_$system_icu_locale_code.sh
	else

    (
				echo 51  # Inicia
				wget --tries=20 "${extralink}/config/locale/l10n_${system_icu_locale_code}.sh" --progress=dot:giga 2>&1 | while read -r line; do
					# Extraindo a porcentagem do progresso do wget
					if [[ $line =~ ([0-9]+)% ]]; then
						percent=${BASH_REMATCH[1]}
						echo $percent  # Atualiza a barra de progresso
					fi
				done

				echo 100  # Finaliza
			) | dialog --gauge "${label_progress}" 6 40 0
		chmod +x l10n_$system_icu_locale_code.sh
    source "l10n_${system_icu_locale_code}.sh"
fi

export USER=$(whoami)
HEIGHT=0
WIDTH=0
CHOICE_HEIGHT=5
BACKTITLE="${label_vncserver_resolution_title}"
TITLE="startvncserver"
MENU="${label_vncserver_resolution_option}"
export PORT=1


OPTIONS=(1 "${label_vncserver_resolution_option_uwhd}"
         2 "${label_vncserver_resolution_option_qdhd}"
         3 "${label_vncserver_resolution_option_fhd}"
         4 "${label_vncserver_resolution_option_hd}"
         5 "${label_vncserver_resolution_option_custom}")



CHOICE=$(dialog --clear \
                --backtitle "$BACKTITLE" \
                --title "$TITLE" \
                --menu "$MENU" \
                $HEIGHT $WIDTH $CHOICE_HEIGHT \
                "${OPTIONS[@]}" \
                2>&1 >/dev/tty)

clear
case $CHOICE in
1)
echo "${label_vncserver_chose_resolution_uwhd}"
GEO="-geometry 2560x1080" vnc
;;
2)
echo "${label_vncserver_chose_resolution_qdhd}"
GEO="-geometry 2560x1440" vnc
;;
3)
echo "${label_vncserver_chose_resolution_fhd}"
GEO="-geometry 1920x1080" vnc
;;
4)
echo "${label_vncserver_chose_resolution_hd}"
GEO="-geometry 1280x720" vnc
;;
5)
echo "${label_vncserver_chose_resolution_custom}"
echo "${label_vncserver_chose_resolution_custom_desc}"
read custom
echo "${label_vncserver_chose_resolution_custom_desc_port}"
read port
GEO="-geometry $custom" PORT=$port vnc
;;
esac

bash --login