#!/bin/bash
source "/usr/local/bin/fixed_variables.sh"

export USER=$(whoami)
HEIGHT=0
WIDTH=0
CHOICE_HEIGHT=5
BACKTITLE="${label_vncserver_resolution_title}"
TITLE="startvncserver"
MENU="${label_vncserver_resolution_option}"
export PORT=1


OPTIONS=(1 "${label_vncserver_resolution_option_uwhd}"
         2 "${label_vncserver_resolution_option_qdhd}"
         3 "${label_vncserver_resolution_option_fhd}"
         4 "${label_vncserver_resolution_option_hd}"
         5 "${label_vncserver_resolution_option_custom}")



CHOICE=$(dialog --clear \
                --backtitle "$BACKTITLE" \
                --title "$TITLE" \
                --menu "$MENU" \
                $HEIGHT $WIDTH $CHOICE_HEIGHT \
                "${OPTIONS[@]}" \
                2>&1 >/dev/tty)

clear
case $CHOICE in
1)
echo "${label_vncserver_chose_resolution_uwhd}"
GEO="-geometry 2560x1080" vnc
;;
2)
echo "${label_vncserver_chose_resolution_qdhd}"
GEO="-geometry 2560x1440" vnc
;;
3)
echo "${label_vncserver_chose_resolution_fhd}"
GEO="-geometry 1920x1080" vnc
;;
4)
echo "${label_vncserver_chose_resolution_hd}"
GEO="-geometry 1280x720" vnc
;;
5)
echo "${label_vncserver_chose_resolution_custom}"
echo "${label_vncserver_chose_resolution_custom_desc}"
read custom
echo "${label_vncserver_chose_resolution_custom_desc_port}"
read port
GEO="-geometry $custom" PORT=$port vnc
;;
esac

bash --login

