#!/bin/bash
source "/usr/local/bin/fixed_variables.sh"

LD_PRELOAD=/lib/aarch64-linux-gnu/libgcc_s.so.1 vncserver -localhost no -depth 24 -name remote-desktop $GEO :$PORT
echo "${label_startvnc_desc} $USER"