#!/bin/bash
source "/usr/local/bin/fixed_variables.sh"

# Solicitar a senha do usuário usando dialog
PASSWORD=$(dialog --title "${label_vnc_setup}" --insecure --passwordbox "${label_vnc_password_input}" 0 0 3>&1 1>&2 2>&3)

# Verificar se o usuário cancelou a entrada
if [ $? != 0 ]; then
    echo "${label_entry_canceled}"
    exit 1
fi

# Salvar a senha no arquivo apropriado
/usr/bin/vncpasswd -f <<<"$PASSWORD"$'\n'"$PASSWORD" > $HOME/.vnc/passwd

# Mensagem de confirmação
#dialog --title "${label_sucess}" --msgbox "${label_change_password}" 0 0

{
    for ((i = 0; i <= 100; i+=2)); do
        sleep 0.08
        echo $i
    done
} | dialog --gauge "${label_change_password}" 6 50 0
clear
